CREATE TABLE IF NOT EXISTS PERSON ( 
 id bigint generated by default as identity (start with 1),
 name varchar(40),
 age integer not null,
 primary key(id)
);

INSERT INTO PERSON (name, age) VALUES ('tom', 27);
